# Generated by Django 3.0.8 on 2020-07-25 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20200725_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextended',
            name='birthday',
            field=models.DateField(),
        ),
    ]
