# Generated by Django 3.0.8 on 2020-08-14 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_auto_20200725_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextended',
            name='gender',
            field=models.TextField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='male'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_author', to='article.UserExtended'),
        ),
    ]
